import 'package:dartz/dartz.dart';

import '../../../../core/domain/errors/failures.dart';
import '../entities/grade_section.dart';
import '../repositories/grade_section_repository.dart';

/// Use case: Create a new grade section
///
/// Called by: ManageGradeSectionsPage (when admin adds a new section)
///
/// Example: Admin adds Section C to Grade 5
class CreateGradeSectionUseCase {
  final GradeSectionRepository repository;

  CreateGradeSectionUseCase({required this.repository});

  Future<Either<Failure, GradeSection>> call({
    required String tenantId,
    required String gradeId,
    required String sectionName,
    required int displayOrder,
  }) async {
    final section = GradeSection(
      id: '', // Will be generated by database
      tenantId: tenantId,
      gradeId: gradeId,
      sectionName: sectionName,
      displayOrder: displayOrder,
      isActive: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    return await repository.createGradeSection(section);
  }
}
