import 'package:dartz/dartz.dart';
import 'package:flutter/material.dart';

import '../../../../core/domain/errors/failures.dart';
import '../entities/exam_timetable_entry.dart';
import '../repositories/exam_timetable_repository.dart';

/// Use case: Add an entry to a timetable
///
/// Called by: ExamTimetableEditPage (admin adds grade/subject/section to timetable)
///
/// Entry = (Grade, Subject, Section, ExamDate, StartTime, EndTime)
/// Example: Grade 5-A Maths on 2024-06-15, 09:00-10:30
///
/// Validation:
/// - Start time < End time
/// - Duration > 0
/// - Entry doesn't already exist (unique constraint)
class AddTimetableEntryUseCase {
  final ExamTimetableRepository repository;

  AddTimetableEntryUseCase({required this.repository});

  Future<Either<Failure, ExamTimetableEntry>> call({
    required String tenantId,
    required String timetableId,
    required String gradeId,
    required String subjectId,
    required String section,
    required DateTime examDate,
    required TimeOfDay startTime,
    required TimeOfDay endTime,
  }) async {
    // Validate start time < end time
    if (startTime.hour > endTime.hour ||
        (startTime.hour == endTime.hour && startTime.minute >= endTime.minute)) {
      return const Left(
        ValidationFailure('Start time must be before end time'),
      );
    }

    // Calculate duration
    final startMinutes = startTime.hour * 60 + startTime.minute;
    final endMinutes = endTime.hour * 60 + endTime.minute;
    final durationMinutes = endMinutes - startMinutes;

    if (durationMinutes <= 0) {
      return const Left(
        ValidationFailure('Exam duration must be greater than 0'),
      );
    }

    // Check if entry already exists
    final existsResult = await repository.entryExists(
      timetableId: timetableId,
      gradeId: gradeId,
      subjectId: subjectId,
      section: section,
    );

    final entryExists = existsResult.fold(
      (failure) => null,
      (exists) => exists,
    );

    if (entryExists == true) {
      return const Left(
        ValidationFailure('Entry for this grade/subject/section already exists'),
      );
    }

    // Create entry
    final entry = ExamTimetableEntry(
      id: '', // Will be generated by database
      tenantId: tenantId,
      timetableId: timetableId,
      gradeId: gradeId,
      subjectId: subjectId,
      section: section,
      examDate: examDate,
      startTime: startTime,
      endTime: endTime,
      durationMinutes: durationMinutes,
      isActive: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    return await repository.addTimetableEntry(entry);
  }
}
