import 'package:dartz/dartz.dart';

import '../../../../core/domain/errors/failures.dart';
import '../entities/exam_timetable.dart';
import '../repositories/exam_timetable_repository.dart';

/// Use case: Create a new exam timetable
///
/// Called by: ExamTimetableCreatePage (admin creates new timetable)
///
/// Can be created:
/// - FROM calendar: Pick from planned exams (June Monthly, etc.)
/// - AD-HOC: Create for daily tests (Week 1, Week 2, etc.)
///
/// Initial status is always "draft"
class CreateExamTimetableUseCase {
  final ExamTimetableRepository repository;

  CreateExamTimetableUseCase({required this.repository});

  Future<Either<Failure, ExamTimetable>> call({
    required String tenantId,
    required String createdBy,
    required String examName,
    required String examType,
    String? examCalendarId,
    int? examNumber,
    required String academicYear,
    Map<String, dynamic>? metadata,
  }) async {
    // Validate exam type
    const validExamTypes = [
      'monthlyTest',
      'quarterlyTest',
      'halfYearlyTest',
      'finalExam',
      'dailyTest'
    ];

    if (!validExamTypes.contains(examType)) {
      return const Left(
        ValidationFailure('Invalid exam type'),
      );
    }

    // For daily tests, examNumber is required
    if (examType == 'dailyTest' && examNumber == null) {
      return const Left(
        ValidationFailure('Daily tests must have an exam number (week)'),
      );
    }

    // Create the timetable
    final timetable = ExamTimetable(
      id: '', // Will be generated by database
      tenantId: tenantId,
      createdBy: createdBy,
      examCalendarId: examCalendarId,
      examName: examName,
      examType: examType,
      examNumber: examNumber,
      academicYear: academicYear,
      status: TimetableStatus.draft,
      publishedAt: null,
      isActive: true,
      metadata: metadata,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    return await repository.createTimetable(timetable);
  }
}
