// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaMDOvGXhfB0H_UENsix-OaWjbYfXe8hY',
    appId: '1:527384772122:web:8aa7775ba839b857f51ba3',
    messagingSenderId: '527384772122',
    projectId: 'papercraft-20d5c',
    authDomain: 'papercraft-20d5c.firebaseapp.com',
    storageBucket: 'papercraft-20d5c.firebasestorage.app',
    measurementId: 'G-8SHSZL25W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK8QckhFogLJVOzC4Xnp7oBaJkfiC72ls',
    appId: '1:527384772122:android:bcdf8f6e00b2d4b7f51ba3',
    messagingSenderId: '527384772122',
    projectId: 'papercraft-20d5c',
    storageBucket: 'papercraft-20d5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKF7IztZdXRh7_k9PLLZ22Eqr0xaL7g-k',
    appId: '1:527384772122:ios:d58cf286db428936f51ba3',
    messagingSenderId: '527384772122',
    projectId: 'papercraft-20d5c',
    storageBucket: 'papercraft-20d5c.firebasestorage.app',
    iosBundleId: 'com.pearl.papercraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKF7IztZdXRh7_k9PLLZ22Eqr0xaL7g-k',
    appId: '1:527384772122:ios:d58cf286db428936f51ba3',
    messagingSenderId: '527384772122',
    projectId: 'papercraft-20d5c',
    storageBucket: 'papercraft-20d5c.firebasestorage.app',
    iosBundleId: 'com.pearl.papercraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaMDOvGXhfB0H_UENsix-OaWjbYfXe8hY',
    appId: '1:527384772122:web:c6ba0b79ed0f7277f51ba3',
    messagingSenderId: '527384772122',
    projectId: 'papercraft-20d5c',
    authDomain: 'papercraft-20d5c.firebaseapp.com',
    storageBucket: 'papercraft-20d5c.firebasestorage.app',
    measurementId: 'G-EDEME3ZK8M',
  );

}