// Mocks generated by Mockito 5.4.6 from annotations
// in papercraft/test/features/exams/domain/usecases/add_timetable_entry_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:papercraft/core/domain/errors/failures.dart' as _i5;
import 'package:papercraft/features/exams/domain/entities/exam_timetable.dart'
    as _i6;
import 'package:papercraft/features/exams/domain/entities/exam_timetable_entry.dart'
    as _i7;
import 'package:papercraft/features/exams/domain/repositories/exam_timetable_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExamTimetableRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamTimetableRepository extends _i1.Mock
    implements _i3.ExamTimetableRepository {
  MockExamTimetableRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ExamTimetable>> createTimetable(
    _i6.ExamTimetable? timetable,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTimetable, [timetable]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ExamTimetable>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ExamTimetable>(
                    this,
                    Invocation.method(#createTimetable, [timetable]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ExamTimetable>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ExamTimetable?>> getTimetableById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTimetableById, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ExamTimetable?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ExamTimetable?>(
                    this,
                    Invocation.method(#getTimetableById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ExamTimetable?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ExamTimetable>>>
  getTimetablesForTenant({
    required String? tenantId,
    String? academicYear,
    _i6.TimetableStatus? status,
    bool? activeOnly = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTimetablesForTenant, [], {
              #tenantId: tenantId,
              #academicYear: academicYear,
              #status: status,
              #activeOnly: activeOnly,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ExamTimetable>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ExamTimetable>>(
                    this,
                    Invocation.method(#getTimetablesForTenant, [], {
                      #tenantId: tenantId,
                      #academicYear: academicYear,
                      #status: status,
                      #activeOnly: activeOnly,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ExamTimetable>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateTimetable(
    _i6.ExamTimetable? timetable,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTimetable, [timetable]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateTimetable, [timetable]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateTimetableStatus({
    required String? timetableId,
    required _i6.TimetableStatus? status,
    DateTime? publishedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTimetableStatus, [], {
              #timetableId: timetableId,
              #status: status,
              #publishedAt: publishedAt,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateTimetableStatus, [], {
                  #timetableId: timetableId,
                  #status: status,
                  #publishedAt: publishedAt,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteTimetable(
    String? timetableId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTimetable, [timetableId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteTimetable, [timetableId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ExamTimetableEntry>> addTimetableEntry(
    _i7.ExamTimetableEntry? entry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTimetableEntry, [entry]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i7.ExamTimetableEntry>
                >.value(
                  _FakeEither_0<_i5.Failure, _i7.ExamTimetableEntry>(
                    this,
                    Invocation.method(#addTimetableEntry, [entry]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.ExamTimetableEntry>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.ExamTimetableEntry>>>
  getTimetableEntries(String? timetableId) =>
      (super.noSuchMethod(
            Invocation.method(#getTimetableEntries, [timetableId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i7.ExamTimetableEntry>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i7.ExamTimetableEntry>>(
                    this,
                    Invocation.method(#getTimetableEntries, [timetableId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.ExamTimetableEntry>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.ExamTimetableEntry>>>
  getTimetableEntriesByGrade({
    required String? timetableId,
    required String? gradeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTimetableEntriesByGrade, [], {
              #timetableId: timetableId,
              #gradeId: gradeId,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i7.ExamTimetableEntry>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i7.ExamTimetableEntry>>(
                    this,
                    Invocation.method(#getTimetableEntriesByGrade, [], {
                      #timetableId: timetableId,
                      #gradeId: gradeId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.ExamTimetableEntry>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ExamTimetableEntry?>>
  getTimetableEntryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTimetableEntryById, [id]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i7.ExamTimetableEntry?>
                >.value(
                  _FakeEither_0<_i5.Failure, _i7.ExamTimetableEntry?>(
                    this,
                    Invocation.method(#getTimetableEntryById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.ExamTimetableEntry?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateTimetableEntry(
    _i7.ExamTimetableEntry? entry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTimetableEntry, [entry]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateTimetableEntry, [entry]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeTimetableEntry(
    String? entryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTimetableEntry, [entryId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#removeTimetableEntry, [entryId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> countTimetableEntries(
    String? timetableId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#countTimetableEntries, [timetableId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
              _FakeEither_0<_i5.Failure, int>(
                this,
                Invocation.method(#countTimetableEntries, [timetableId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> entryExists({
    required String? timetableId,
    required String? gradeId,
    required String? subjectId,
    required String? section,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#entryExists, [], {
              #timetableId: timetableId,
              #gradeId: gradeId,
              #subjectId: subjectId,
              #section: section,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#entryExists, [], {
                  #timetableId: timetableId,
                  #gradeId: gradeId,
                  #subjectId: subjectId,
                  #section: section,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.PaperCountResult>>
  calculateExpectedPaperCount({required String? timetableId}) =>
      (super.noSuchMethod(
            Invocation.method(#calculateExpectedPaperCount, [], {
              #timetableId: timetableId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i3.PaperCountResult>>.value(
                  _FakeEither_0<_i5.Failure, _i3.PaperCountResult>(
                    this,
                    Invocation.method(#calculateExpectedPaperCount, [], {
                      #timetableId: timetableId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i3.PaperCountResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i3.ValidationError>>>
  validateForPublishing({required String? timetableId}) =>
      (super.noSuchMethod(
            Invocation.method(#validateForPublishing, [], {
              #timetableId: timetableId,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i3.ValidationError>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i3.ValidationError>>(
                    this,
                    Invocation.method(#validateForPublishing, [], {
                      #timetableId: timetableId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i3.ValidationError>>>);
}
